# REPO_URL|FOLDER_NAME|BRANCH
https://github.com/Sagiroth/TortoiseBots.git|TortoiseBots|main
https://github.com/Penqle/tw-mod-autoscale.git|tw-mod-autoscale|main
https://github.com/Penqle/tw-mod-leech.git|tw-mod-leech|master
https://github.com/dr1s/tw-mod-hearthstone-cooldown.git|tw-mod-hearthstone-cooldown|main
https://github.com/dr1s/tw-mod-worldbuff-timer.git|tw-mod-worldbuff-timer|main
https://github.com/dr1s/tw-mod-attunement-skip.git|tw-mod-attunement-skip|main
https://github.com/dr1s/tw-mod-corpse-respawn.git|tw-mod-corpse-respawn|main
https://github.com/dr1s/tw-mod-instant-flight.git|tw-mod-instant-flight|main
https://github.com/dr1s/tw-mod-autolearn-spells.git|tw-mod-autolearn-spells|main
https://github.com/dr1s/tw-mod-aoe-loot.git|tw-mod-aoe-loot|master
https://github.com/dr1s/tw-mod-loot-multiplier.git|tw-mod-loot-multiplier|main
